BEGIN;
DELETE FROM tasks WHERE parameters -> 'generator' = 'control';

INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => invalid.noise.gatech.edu, origin => "http://invalid.noise.gatech.edu", url => "http://invalid.noise.gatech.edu", imageUrl => "http://invalid.noise.gatech.edu", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu", url => "http://encore.noise.gatech.edu/nonexistent.png", imageUrl => "http://encore.noise.gatech.edu/nonexistent.png", control => "dnsRedirect"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => blackhole.noise.gatech.edu, origin => "http://blackhole.noise.gatech.edu", url => "http://blackhole.noise.gatech.edu", imageUrl => "http://blackhole.noise.gatech.edu", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8888", url => "http://encore.noise.gatech.edu:8888/pixel.png", imageUrl => "http://encore.noise.gatech.edu:8888/pixel.png", control => "ipBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8889", url => "http://encore.noise.gatech.edu:8889/pixel.png", imageUrl => "http://encore.noise.gatech.edu:8889/pixel.png", control => "httpDropping"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8890", url => "http://encore.noise.gatech.edu:8890/pixel.png", imageUrl => "http://encore.noise.gatech.edu:8890/pixel.png", control => "tcpResetIp"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8891", url => "http://encore.noise.gatech.edu:8891/pixel.png", imageUrl => "http://encore.noise.gatech.edu:8891/pixel.png", control => "tcpResetUrl"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => img, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8892", url => "http://encore.noise.gatech.edu:8892/pixel.png", imageUrl => "http://encore.noise.gatech.edu:8892/pixel.png", control => "baseline"')::hstore);

INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => invalid.noise.gatech.edu, origin => "http://invalid.noise.gatech.edu", url => "http://invalid.noise.gatech.edu/pixel.png", scriptUrl => "http://invalid.noise.gatech.edu/pixel.png", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu", url => "http://encore.noise.gatech.edu/nonexistent.png", scriptUrl => "http://encore.noise.gatech.edu/nonexistent.png", control => "dnsRedirect"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => blackhole.noise.gatech.edu, origin => "http://blackhole.noise.gatech.edu", url => "http://blackhole.noise.gatech.edu", scriptUrl => "http://blackhole.noise.gatech.edu", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8888", url => "http://encore.noise.gatech.edu:8888/pixel.png", scriptUrl => "http://encore.noise.gatech.edu:8888/pixel.png", control => "ipBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8889", url => "http://encore.noise.gatech.edu:8889/pixel.png", scriptUrl => "http://encore.noise.gatech.edu:8889/pixel.png", control => "httpDropping"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8890", url => "http://encore.noise.gatech.edu:8890/pixel.png", scriptUrl => "http://encore.noise.gatech.edu:8890/pixel.png", control => "tcpResetIp"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8891", url => "http://encore.noise.gatech.edu:8891/pixel.png", scriptUrl => "http://encore.noise.gatech.edu:8891/pixel.png", control => "tcpResetUrl"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => script, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8892", url => "http://encore.noise.gatech.edu:8892/pixel.png", scriptUrl => "http://encore.noise.gatech.edu:8892/pixel.png", control => "baseline"')::hstore);

INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => invalid.noise.gatech.edu, origin => "http://invalid.noise.gatech.edu", url => "http://invalid.noise.gatech.edu/style.css", cssUrl => "http://invalid.noise.gatech.edu/style.css", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu", url => "http://encore.noise.gatech.edu/nonexistent.png", cssUrl => "http://encore.noise.gatech.edu/nonexistent.png", control => "dnsRedirect"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => blackhole.noise.gatech.edu, origin => "http://blackhole.noise.gatech.edu", url => "http://blackhole.noise.gatech.edu", cssUrl => "http://blackhole.noise.gatech.edu", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8888", url => "http://encore.noise.gatech.edu:8888/style.css", cssUrl => "http://encore.noise.gatech.edu:8888/style.css", control => "ipBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8889", url => "http://encore.noise.gatech.edu:8889/style.css", cssUrl => "http://encore.noise.gatech.edu:8889/style.css", control => "httpDropping"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8890", url => "http://encore.noise.gatech.edu:8890/style.css", cssUrl => "http://encore.noise.gatech.edu:8890/style.css", control => "tcpResetIp"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8891", url => "http://encore.noise.gatech.edu:8891/style.css", cssUrl => "http://encore.noise.gatech.edu:8891/style.css", control => "tcpResetUrl"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => css, generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8892", url => "http://encore.noise.gatech.edu:8892/style.css", cssUrl => "http://encore.noise.gatech.edu:8892/style.css", control => "baseline"')::hstore);

INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => invalid.noise.gatech.edu, origin => "http://invalid.noise.gatech.edu", url => "http://invalid.noise.gatech.edu/page.html", iframeUrl => "http://invalid.noise.gatech.edu/page.html", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu", url => "http://encore.noise.gatech.edu/nonexistent.png", iframeUrl => "http://encore.noise.gatech.edu/nonexistent.png", control => "dnsRedirect"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => blackhole.noise.gatech.edu, origin => "http://blackhole.noise.gatech.edu", url => "http://blackhole.noise.gatech.edu", iframeUrl => "http://blackhole.noise.gatech.edu", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8888", url => "http://encore.noise.gatech.edu:8888/page.html", iframeUrl => "http://encore.noise.gatech.edu:8888/page.html", control => "ipBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8889", url => "http://encore.noise.gatech.edu:8889/page.html", iframeUrl => "http://encore.noise.gatech.edu:8889/page.html", control => "httpDropping"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8890", url => "http://encore.noise.gatech.edu:8890/page.html", iframeUrl => "http://encore.noise.gatech.edu:8890/page.html", control => "tcpResetIp"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8891", url => "http://encore.noise.gatech.edu:8891/page.html", iframeUrl => "http://encore.noise.gatech.edu:8891/page.html", control => "tcpResetUrl"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-load", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8892", url => "http://encore.noise.gatech.edu:8892/page.html", iframeUrl => "http://encore.noise.gatech.edu:8892/page.html", control => "baseline"')::hstore);

INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => invalid.noise.gatech.edu, origin => "http://invalid.noise.gatech.edu", url => "http://invalid.noise.gatech.edu/page.html", iframeUrl => "http://invalid.noise.gatech.edu/page.html", imageUrl => "http://invalid.noise.gatech.edu/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu", url => "http://encore.noise.gatech.edu/nonexistent.png", iframeUrl => "http://encore.noise.gatech.edu/nonexistent.png", imageUrl => "http://encore.noise.gatech.edu/nonexistent.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "dnsRedirect"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => blackhole.noise.gatech.edu, origin => "http://blackhole.noise.gatech.edu", url => "http://blackhole.noise.gatech.edu", iframeUrl => "http://blackhole.noise.gatech.edu", imageUrl => "http://blackhole.noise.gatech.edu", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8888", url => "http://encore.noise.gatech.edu:8888/page.html", iframeUrl => "http://encore.noise.gatech.edu:8888/page.html", imageUrl => "http://encore.noise.gatech.edu:8888/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "ipBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8889", url => "http://encore.noise.gatech.edu:8889/page.html", iframeUrl => "http://encore.noise.gatech.edu:8889/page.html", imageUrl => "http://encore.noise.gatech.edu:8889/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "httpDropping"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8890", url => "http://encore.noise.gatech.edu:8890/page.html", iframeUrl => "http://encore.noise.gatech.edu:8890/page.html", imageUrl => "http://encore.noise.gatech.edu:8890/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "tcpResetIp"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8891", url => "http://encore.noise.gatech.edu:8891/page.html", iframeUrl => "http://encore.noise.gatech.edu:8891/page.html", imageUrl => "http://encore.noise.gatech.edu:8891/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "tcpResetUrl"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8892", url => "http://encore.noise.gatech.edu:8892/page.html", iframeUrl => "http://encore.noise.gatech.edu:8892/page.html", imageUrl => "http://encore.noise.gatech.edu:8892/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "baseline"')::hstore);

INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => invalid.noise.gatech.edu, origin => "http://invalid.noise.gatech.edu", url => "http://invalid.noise.gatech.edu/cross.html", iframeUrl => "http://invalid.noise.gatech.edu/cross.html", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu", url => "http://encore.noise.gatech.edu/nonexistent.png", iframeUrl => "http://encore.noise.gatech.edu/nonexistent.png", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "dnsRedirect"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => blackhole.noise.gatech.edu, origin => "http://blackhole.noise.gatech.edu", url => "http://blackhole.noise.gatech.edu", iframeUrl => "http://blackhole.noise.gatech.edu", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "dnsBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8888", url => "http://encore.noise.gatech.edu:8888/cross.html", iframeUrl => "http://encore.noise.gatech.edu:8888/cross.html", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "ipBlocking"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8889", url => "http://encore.noise.gatech.edu:8889/cross.html", iframeUrl => "http://encore.noise.gatech.edu:8889/cross.html", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "httpDropping"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8890", url => "http://encore.noise.gatech.edu:8890/cross.html", iframeUrl => "http://encore.noise.gatech.edu:8890/cross.html", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "tcpResetIp"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8891", url => "http://encore.noise.gatech.edu:8891/cross.html", iframeUrl => "http://encore.noise.gatech.edu:8891/cross.html", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "tcpResetUrl"')::hstore);
INSERT INTO tasks (parameters) values (('taskType => "iframe-cache", generator => control, generationRun => "' || to_char(now(), 'YYYY-MM-DD"T"HH:MM:SS"Z"') || '", scheme => http, host => encore.noise.gatech.edu, origin => "http://encore.noise.gatech.edu:8892", url => "http://encore.noise.gatech.edu:8892/cross.html", iframeUrl => "http://encore.noise.gatech.edu:8892/cross.html", imageUrl => "http://encore.noise.gatech.edu:8893/pixel.png", controlImageUrl => "http://encore.noise.gatech.edu:8894/pixel.png", control => "baseline"')::hstore);

COMMIT;
